name: Create release branch
on: 
  workflow_dispatch:
    inputs:
      dev_branch:
        description: The source branch to create the dev branch from.
        required: false
        default: 'main'
      release_branch:
        description: The name of the release branch to create.
        required: true
        default: 'release'

jobs:
  CreateBranchNew:
    name: Create Branch
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#       - name: Create release branch
#         env:
#           DEV_BRANCH: ${{ github.event.inputs.dev_branch }}
#           RELEASE_BRANCH: ${{ github.event.inputs.release_branch }}
#         run: |
#           git fetch origin
#           git checkout -b ${RELEASE_BRANCH} origin/${DEV_BRANCH} && git push --set-upstream origin ${RELEASE_BRANCH}
          
      - name: Create release branch
        env:
          DEV_BRANCH: ${{ github.event.inputs.dev_branch }}
          RELEASE_BRANCH: ${{ github.event.inputs.release_branch }}
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_ACTOR}"
          curl -X POST \
            ${{ github.api_url }}/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/git/refs \
            -H 'Authorization: Bearer ${{ env.GIT_TOKEN }}' \
            -H "Accept: application/vnd.github+json" \
            -d '{"ref":"refs/heads/${{ env.RELEASE_BRANCH }}","sha":"${{ github.sha }}"}'
