# This is a basic workflow to help you get started with Actions
name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run build
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
